# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy remaining source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not required for stdio transport)

# Start the MCP server
CMD ["node", "build/index.js"]
